### ISSUE TITLE
Chaining multiple selects

### ISSUE THREAD

**Issue by martenwilmink** [Qaraqter/simpletope#6]
The current filter can chain multiple selects by 'AND'. In the case of a dropdown, (re-)selecting a filter adds the selection to the filter, thus singling out too many options in chained single select filters.

TODO @PabloDeGrote 
- Add the `data-filter-chain="yourGroupName"` to SimpleTope

**Comment by PabloDeGrote** [comment]
Fix staat klaar op github en bower :)
